### ISSUE TITLE
How can I calculate the OSI and TAWSS with haemoFoam?

### ISSUE THREAD

**Issue by lilux618** [TS-CUBED/haemoFoam#31]
I want to calculate OSI TAWSS quickly, what should I do by using this solver？

**Comment by TS-CUBED** [comment]
If all you need to do is calculate the WSS metrics and you don't need the viscosity models in haemoFoam, then you can simply run the `haemoPostProcess` command.

It's a two step process:

1. calculate the WSS, e.g., with a function object or running, e.g., `pimpleFoam --postProcess --func wallShearStress` (from memory, command may be slightly different)

2. calculate OSI, TAWSS, etc. using `haemoPostProcess` from this package.

See section "Function Objects" and "Post Processing" in the documentation in the `docs` folder.

**Comment by lilux618** [comment]
Thank you very much! It looks like some additional files are needed to run this program compared to pimpleFoam. Many researchers like me would want to be able to easily modify pimpleFoam files to apply haemoFoam, so it would be very helpful if a guide could be provided.

**Comment by lilux618** [comment]
If I want to use haemoPostProcess to calculate the OSI based on the raw pimplefoam calculation, it seems I need to put the H file in the per-time results folder, even though I don't need the H file.   Is there a simpler way?

**Comment by TS-CUBED** [comment]
Not at the moment, since `haemoPostProcess` also calculates the average haematocrit and is not initially intended to run on anything but `haemoFoam` results.

So you'll either, for the moment, need to copy the H file to all the time directories (should be a one liner for the shell:

```
$ for dir in [0-9]*; do
cp 0/H $dir/ 
done
```

OK, that's three lines, but you could do it in one. It also doesn't check if the `[0-9]` is actually a directory, and you'll get an error regarding `0/H`. But it does work.

You could also modify `haemoPostProcess` to take the `H` out of the postprocessing loop.

I'll keep that on the list for a future release and will add a check if H exists and not average it if it doesn't. 

It seems the postprocessing is a thing that many want to use without actually needing the haemoFoam solver itself, so there is a good rationale behind that improvement,

**Comment by lilux618** [comment]
Thank you very much, it works!   Before that, I tried to use haemoPimpleFoam to do the calculation, I did not make a complete comparison, can it completely replace pimpleFoam?

**Comment by TS-CUBED** [comment]
If you switch the haematocrit transport off and fine use one of the new viscosity models, it should be equivalent to normal pimpleFoam.

It is based on pimpleFoam, bit doesn't track it, so changes to pimpleFoam after I branches it off in 2018 won't be reflected.

The only change to the case will be that you need a H file (cannot switch off the H equation completely, just disable the transport, i.e., freeze the field), haemoTransportProperties, and rho in transportProperties. Otherwise you should be able to simply drop in a pimpleFoam case.

On the other hand there's no benefit to using haemoPimpleFoam in that case.

**Comment by TS-CUBED** [comment]
Adendum: the Quemada model is getting more traction in the community at the moment, and it can easily be used with a constant haematocrit. So using haemoFoam may be the quickest way to get the Quemada model working. Just set the `haemoSwitch` to `0` and freeze the H equation, then it will just use the initial value set in `0/H` for the whole field.
